### ISSUE TITLE
appending to an array

### ISSUE THREAD

**Issue by jonathanstrong** [bluss/ndarray#433]
This seems simple, but I can't seem to find an answer in the docs: what is the idiomatic way of appending data to an array, like you would with `Vec::push`? In my situation, I'm pulling in realtime data from different places and processing it for data analysis; it should end up eventually in an `Array2`.

**Comment by jturner314** [comment]
There currently isn't any way to directly enlarge arrays in-place like you can with `Vec::push`. (See #387.)

However, these are a few options for your specific situation:

1. Use the [`stack()` function](https://docs.rs/ndarray/0.11.2/ndarray/fn.stack.html) or [`stack![]` macro](https://docs.rs/ndarray/0.11.2/ndarray/macro.stack.html). The disadvantage is that they copy all of the data into a new array, so they're pretty expensive.

2. Push the data to a `Vec` in real-time, and then convert it to an `Array` at the end with [`Array::from_shape_vec()`](https://docs.rs/ndarray/0.11.2/ndarray/struct.ArrayBase.html#method.from_shape_vec). (If you need to do intermediate processing using `ndarray` on the data in real time, you can create `ArrayView`/`ArrayViewMut` instances from slices of the data with [`ArrayView::from_shape()`](https://docs.rs/ndarray/0.11.2/ndarray/type.ArrayView.html#method.from_shape)/[`ArrayViewMut::from_shape()`](https://docs.rs/ndarray/0.11.2/ndarray/type.ArrayViewMut.html#method.from_shape).) This approach is efficient because the `Vec` can enlarge efficiently, and `from_shape_vec`/`from_shape` don't clone the elements.

3. If you know ahead-of-time how much data you're going to collect, you can allocate an `Array` (e.g. using [`Array::zeros()`](https://docs.rs/ndarray/0.11.2/ndarray/struct.ArrayBase.html#method.zeros)) for all of the data at the beginning, and then assign the data points to rows in the array as they come in (keeping track of how much data you've added so far with a separate variable).

**Comment by jturner314** [comment]
Yeah, `ArrayView` instances are cheap, especially fixed-dimension views and dynamic-dimension views with four dimensions or less. (Dynamic-dimension views with more than four dimensions are a little more expensive because they require heap allocations for the shape and strides.) For example, a 2-D fixed-dimension `ArrayView` is just 40 stack-allocated bytes on a 64-bit machine (0 bytes for the lifetime + 8 bytes for the pointer to the first element + (8 * 2) bytes for the shape + (8 * 2) bytes for the strides).

Regarding strides, if you go with option 2 of pushing the data to a `Vec`, then you can push row-by-row and use `::from_shape_vec()` with the default memory layout (row-major). For example:

```rust
let mut data = Vec::new();
data.extend_from_slice(&[1, 2, 3]);
data.extend_from_slice(&[4, 5, 6]);
assert_eq!(
    Array::from_shape_vec((2, 3), data).unwrap(),
    array![[1, 2, 3],
           [4, 5, 6]],
);
```

If you want to grow by columns instead of rows, you can specify that you want an array with column-major layout by calling `.f()` on the shape:

```rust
let mut data = Vec::new();
data.extend_from_slice(&[1, 4]);
data.extend_from_slice(&[2, 5]);
data.extend_from_slice(&[3, 6]);
assert_eq!(
    Array::from_shape_vec((2, 3).f(), data).unwrap(),
    array![[1, 2, 3],
           [4, 5, 6]],
);
```

**Comment by jturner314** [comment]
This question seems to be resolved, so I'm closing the issue. If you have more questions, please feel free to reopen the issue.

For anyone wishing to add the ability to resize `Array` instances directly in-place, please create a new issue for that feature with a design proposal.
