### ISSUE TITLE
scalar_prod implementation

### ISSUE THREAD

**Issue by sebasv** [bluss/ndarray#504]
I am missing a scalar_prod function. on ArrayBase. This seems straightforward to implement (almost blindly copy/paste scalar_sum), so I will be submitting a pull request. I am not familiar enough with computer engineering to say if an unrolled_prod is a valuable addition as well, so I will just include it in the PR awaiting feedback from someone with more background!

**Comment by jturner314** [comment]
> I am not familiar enough with computer engineering to say if an unrolled_prod is a valuable addition as well

If you're interested, [this is a pretty good article for background](https://docs.microsoft.com/en-us/cpp/build/reference/floating-point-optimization), even though it's talking about C++ with the MS compiler instead of Rust with LLVM. Basically, in order to allow the compiler to perform the sum/product using SIMD even with strict floating-point behavior, it's helpful to explicitly unroll and reorder the sum/product manually.

**Comment by sebasv** [comment]
That seems like a very nice read, thank you!

**Comment by jturner314** [comment]
Implemented in #505.
